### ISSUE TITLE
New Builds to Add

### ISSUE THREAD

**Issue by berdandy** [accessibilitywars/aw2-builds#10]
- [x] https://www.youtube.com/watch?v=AaPuiW0ulGM (Bladesworn)
- [x] https://www.youtube.com/watch?v=rS2ogstNepI (Soulbeast)

**Comment by berdandy** [comment]
Soulbeast added

**Comment by MuwuM** [comment]
Bladesworn was added in https://github.com/accessibilitywars/aw2-builds/pull/12

**Comment by MuwuM** [comment]
- [x] https://www.youtube.com/watch?v=Qqmc3Rzkd0M (LI Willbender by Mukluk)

**Comment by berdandy** [comment]
Closing -- all builds added. Reopen when new builds show up.

**Comment by berdandy** [comment]
More!

- [ ] MrMystic Holosmith - https://youtu.be/hGYoURAIPxc (also needs Author entry)
- [x] MuwM Heal Chrono - https://www.youtube.com/watch?v=rSFKhZA54UA

**Comment by berdandy** [comment]
Hm. I think I'm going to make separate issues for individual builds, one for each build. Easier to close with commit messages.
